apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-app
spec:
  selector:
    matchLabels:
      app: supabase-app
  template:
    metadata:
      labels:
        app: supabase-app
    spec:
      containers:
        - name: supabase-app
          image: bohdanpn/supabase-app
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
          - mountPath: /supabase-project/.env.local
            name: env-local
            readOnly: true
            subPath: .env.local
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: .env
            path: .env.local
          name: env-local
        name: env-local
      restartPolicy: Always